### ISSUE TITLE
Run locally without SSL certificate?

### ISSUE THREAD

**Issue by hueykwik** [osk2/pitch-analyzer#1]
Hi, I just want to test out the app on my own machine. Do you have instructions on how to do this without requiring an SSL cert?

**Comment by osk2** [comment]
Hi, I haven't try this myself but you can do following:

1. https://stackoverflow.com/a/56930009
2. Change line 107-109 of [index.js](https://github.com/osk2/pitch-analyzer/blob/master/index.js) to

```js
app.listen(3000, function () {
  console.log('Listening on port 3000');
});
```

**Comment by hueykwik** [comment]
I made some progress, but I still can't actually test my pronunciation.

Here's what I did to get up and running:
1. Added a whitelist for `localhost`
2. Changed `index.js` to use `app.listen`
3. Commented out `sslOptions` on lines 16-20

Now the app runs, but I can't seem to test my pronunciation yet:

![image](https://user-images.githubusercontent.com/707311/124373816-31ae2b80-dcc8-11eb-9fad-8081379031c0.png)

Is this related to the part of the README that suggested I need to add my own levels? I went to `upload.html` but it wasn't clear to me what I should do there. 

I also checked the permissions on `/public/upload`:
drw-rw-r--   3 huey  staff     96 Jul  3 14:33 upload

What should be my next step?

**Comment by osk2** [comment]
You should upload audio file via `/upload.html` first to create levels. After that you should be able to start the test.

**Comment by hueykwik** [comment]
What kind of audio files do I need to upload?

**Comment by osk2** [comment]
IIRC format should be .wav
If you are asking content of audio file. Then it should be pronunciation of a word

**Comment by hueykwik** [comment]
Here's a 1-min video of my getting an error when I try to upload a .wav file: 

https://www.loom.com/share/9ae59f94339b4da08fbeeb2476ed2ca9

**Comment by osk2** [comment]
What's the content of questions.json? Error message shows that questions.json is not a valid JSON.

**Comment by hueykwik** [comment]
It's empty.

**Comment by osk2** [comment]
Ah that's the problem. Try to change content of questions.json to `[]`.

**Comment by hueykwik** [comment]
Getting closer! I changed the content of questions.json to an empty array, but now I get this error when I try to upload:

```
Error: EACCES: permission denied, open 'public/upload/nv3er2.wav'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at WriteStream.onerror (_stream_readable.js:754:7)
    at WriteStream.emit (events.js:314:20)
    at internal/fs/streams.js:361:12
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'public/upload/nv3er2.wav'
}
```
drw-rw-r--   4 huey  staff    128 Jul  4 13:28 upload

**Comment by osk2** [comment]
Try `chmod 777 public/upload` instead 664?

**Comment by hueykwik** [comment]
That worked! Thanks for all your help.
